import Head from 'next/head'
import Link from 'next/link'
import { UserButton, SignInButton, useUser } from '@clerk/nextjs'
import { api } from '~/utils/api'
import { useEffect } from 'react'

export default function Home() {
    const user = useUser()

    const { data } = api.posts.getAll.useQuery()

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {user.isSignedIn && (
                <header className="flex flex-row-reverse py-2">
                    <div className="px-2 py-1 mr-1">
                        <UserButton afterSignOutUrl="/" />
                    </div>
                </header>
            )}

            <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
                {!user.isSignedIn && (
                    <div className="rounded-sm m-1 px-2 py-1 text-white bg-emerald-900">
                        <SignInButton />
                    </div>
                )}
                {data?.map((post) => {
                    return (
                        <div key={post.id}>
                            <h1>{post.title}</h1>
                            <p>{post.content}</p>
                        </div>
                    )
                })}
            </main>
        </>
    )
}
